# Generated by Django 5.1.3 on 2026-02-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albumapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="album",
            name="user",
        ),
    ]
