# Generated by Django 5.1.3 on 2026-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albumapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
