# Generated by Django 5.1.3 on 2026-01-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albumapp", "0002_remove_photo_is_favorite_album_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
