# Generated by Django 5.1.1 on 2025-11-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('height', models.FloatField(verbose_name='身長（cm）')),
                ('weight', models.FloatField(verbose_name='体重（kg）')),
                ('baby_log', models.TextField(max_length=150, verbose_name='発達状況')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
            ],
        ),
    ]
