# Generated by Django 5.1.1 on 2026-01-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growthapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='weight',
        ),
    ]
