# Generated by Django 5.1.3 on 2026-01-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growthapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="growthrecord",
            name="height",
        ),
        migrations.RemoveField(
            model_name="growthrecord",
            name="weight",
        ),
    ]
