<<<<<<< HEAD
# Generated by Django 5.1.3 on 2026-01-28 01:15
=======
# Generated by Django 5.1.1 on 2026-01-27 02:05
>>>>>>> a5ce910dbe9f633f8d03ad78a0a5ab9e140b5502

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("growthapp", "0001_initial"),
=======
        ('growthapp', '0001_initial'),
>>>>>>> a5ce910dbe9f633f8d03ad78a0a5ab9e140b5502
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name="growthrecord",
            name="height",
        ),
        migrations.RemoveField(
            model_name="growthrecord",
            name="weight",
=======
            model_name='growthrecord',
            name='height',
        ),
        migrations.RemoveField(
            model_name='growthrecord',
            name='weight',
>>>>>>> a5ce910dbe9f633f8d03ad78a0a5ab9e140b5502
        ),
    ]
