# Generated by Django 5.1.1 on 2026-01-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthapp', '0002_remove_growthrecord_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='name',
            field=models.CharField(default='未設定', max_length=50, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
