# Generated by Django 5.1.1 on 2026-01-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthapp', '0003_growthrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthrecord',
            name='name',
            field=models.CharField(default='未設定', max_length=50, verbose_name='名前'),
        ),
    ]
