<<<<<<< HEAD
# Generated by Django 5.1.3 on 2026-01-22 14:22
=======
# Generated by Django 5.1.2 on 2026-01-15 02:20
>>>>>>> d2e9e600ff1358885fb543abe22d61f09b026133

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("calendarapp", "0002_calendarday_dayentry_delete_dailyrecord"),
=======
        ('calendarapp', '0002_calendarday_dayentry_delete_dailyrecord'),
>>>>>>> d2e9e600ff1358885fb543abe22d61f09b026133
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("image", models.ImageField(upload_to="photos/")),
                ("comment", models.TextField(blank=True)),
=======
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('comment', models.TextField(blank=True)),
>>>>>>> d2e9e600ff1358885fb543abe22d61f09b026133
            ],
        ),
    ]
