# Generated by Django 5.1.2 on 2026-01-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_calendarday_dayentry_delete_dailyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
