# Generated by Django 5.1.2 on 2026-02-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
    ]
