# Generated by Django 5.1.3 on 2026-01-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="icon",
        ),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="アイコン",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
