# Generated by Django 5.1.3 on 2026-01-27 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_icon_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/', verbose_name='アイコン画像'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('not_specified', '未設定')], default='not_specified', max_length=20, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='プロフィール画像')),
                ('icon_color', models.CharField(blank=True, default='#667eea', help_text='画像未設定時のアイコン背景色', max_length=7, verbose_name='アイコンカラー')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': 'アカウント',
            },
        ),
    ]
