# Generated by Django 5.1.3 on 2026-01-29 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_icon_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='表示名')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('not_specified', '未設定')], default='not_specified', max_length=20, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='multi_profiles', verbose_name='プロフィール画像')),
                ('icon_color', models.CharField(default='#667eea', max_length=7, verbose_name='アイコンカラー')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
